(() => {
"use strict";
const money=new Intl.NumberFormat("es-MX",{style:"currency",currency:"MXN"});
const date=new Intl.DateTimeFormat("es-MX",{dateStyle:"medium",timeStyle:"short"});
function el(t,c="",x=""){const n=document.createElement(t);if(c)n.className=c;if(x!=="")n.textContent=x;return n;}
function metric(label,value,detail){const n=el("article","gift-admin-metric");n.append(el("p","gift-admin-metric-label",label),el("strong","gift-admin-metric-value",value),el("span","gift-admin-metric-detail",detail));return n;}
function openConfirm(item,refresh){const ov=el("div","finance-modal-overlay"),dlg=el("section","finance-modal");dlg.setAttribute("role","dialog");dlg.setAttribute("aria-modal","true");const h=el("header","finance-modal-head"),copy=el("div");copy.append(el("p","admin-eyebrow","Mesa de regalos"),el("h2","","Confirmar transferencia"));const close=el("button","admin-button admin-button-secondary","Cerrar");close.type="button";h.append(copy,close);const form=el("form","finance-form"),grid=el("div","finance-form-grid finance-form-grid-single"),info=el("p","gift-admin-modal-info",`${item.invitado} · ${item.codigo}`),amount=document.createElement("input"),notes=document.createElement("textarea");amount.type="number";amount.min="0";amount.step="0.01";amount.required=true;amount.placeholder="Monto recibido";notes.rows=3;notes.placeholder="Nota opcional";const f1=el("label","finance-field"),f2=el("label","finance-field");f1.append(el("span","","Monto confirmado *"),amount);f2.append(el("span","","Notas"),notes);grid.append(info,f1,f2);const status=el("p","finance-form-status"),actions=el("div","finance-form-actions"),cancel=el("button","admin-button admin-button-secondary","Cancelar"),save=el("button","admin-button","Confirmar transferencia");cancel.type="button";save.type="submit";actions.append(cancel,save);form.append(grid,status,actions);dlg.append(h,form);ov.append(dlg);document.body.append(ov);document.body.classList.add("finance-modal-open");const dismiss=()=>{ov.remove();document.body.classList.remove("finance-modal-open")};close.onclick=cancel.onclick=dismiss;ov.addEventListener("mousedown",e=>{if(e.target===ov)dismiss()});form.onsubmit=async e=>{e.preventDefault();save.disabled=true;status.textContent="Guardando…";try{await window.AdminGiftService.confirm(item.id,amount.value,notes.value);dismiss();await refresh();}catch(err){status.textContent=err?.message||"No fue posible confirmar la transferencia.";save.disabled=false;}};}
window.AdminViews=window.AdminViews||{};
window.AdminViews.regalos=function(){const root=el("section","gift-admin-view"),head=el("header","admin-view-header");head.append(el("p","admin-eyebrow","Finanzas"),el("h2","","Mesa de regalos"),el("p","admin-view-copy","Señales de invitados que copiaron la CLABE. Una copia indica intención; confirma manualmente el depósito después de revisarlo en tu cuenta bancaria."));const feedback=el("p","gift-admin-feedback"),metrics=el("div","gift-admin-metrics"),panel=el("section","gift-admin-panel");root.append(head,metrics,feedback,panel);async function load(){feedback.textContent="Actualizando…";try{const data=await window.AdminGiftService.getSummary(),r=data.resumen||{},items=data.registros||[];metrics.replaceChildren(metric("CLABE copiada",String(r.clabe_copiada||0),"invitaciones con señal"),metric("Por verificar",String(r.por_verificar||0),"posibles transferencias"),metric("Confirmadas",String(r.confirmadas||0),"depósitos verificados"),metric("Monto confirmado",money.format(Number(r.monto_confirmado||0)),"regalos recibidos"));panel.replaceChildren();if(!items.length){panel.append(el("p","gift-admin-empty","Aún no hay invitaciones que hayan copiado la CLABE."));}else{const wrap=el("div","gift-admin-table-wrap"),table=el("table","gift-admin-table"),thead=document.createElement("thead"),tr=document.createElement("tr");["Invitado","Código","Última copia","Copias","Estado","Monto","Acción"].forEach(x=>tr.append(el("th","",x)));thead.append(tr);const tbody=document.createElement("tbody");items.forEach(item=>{const row=document.createElement("tr");row.append(el("td","",item.invitado),el("td","",item.codigo),el("td","",date.format(new Date(item.ultima_copia))),el("td","",String(item.veces_copiada)),el("td",item.estado==="confirmada"?"gift-admin-status confirmed":"gift-admin-status pending",item.estado==="confirmada"?"Confirmada":"Por verificar"),el("td","",item.estado==="confirmada"?money.format(Number(item.monto_confirmado||0)):"—"));const action=document.createElement("td"),btn=el("button",item.estado==="confirmada"?"admin-button admin-button-secondary":"admin-button",item.estado==="confirmada"?"Reabrir":"Confirmar");btn.type="button";btn.onclick=async()=>{if(item.estado==="confirmada"){if(!confirm(`¿Marcar nuevamente como por verificar la transferencia de ${item.invitado}?`))return;await window.AdminGiftService.reopen(item.id);await load();}else openConfirm(item,load);};action.append(btn);row.append(action);tbody.append(row);});table.append(thead,tbody);wrap.append(table);panel.append(wrap);}feedback.textContent=`${items.length} invitaciones con señal de transferencia.`;}catch(err){console.error(err);feedback.textContent=err?.message||"No fue posible cargar Mesa de regalos.";}}load();return root;};
})();
