(() => {
  "use strict";
  const elements={};let authSubscription=null;let resolving=false;let routerStarted=false;
  function resolveElements(){["adminLogin","adminLoginForm","adminEmail","adminPassword","adminLoginButton","adminLoginMessage","adminShell","adminName","adminRole","adminLogoutButton","adminFatal","adminFatalMessage","adminRouteView","adminMenuButton","adminSidebarBackdrop"].forEach((id)=>{elements[id]=document.querySelector(`#${id}`);});return Object.values(elements).every(Boolean);}
  function hideAll(){elements.adminLogin.hidden=true;elements.adminShell.hidden=true;elements.adminFatal.hidden=true;}
  function stopRouter(){if(routerStarted){window.AdminRouter.stop();routerStarted=false;}}
  function showLogin(message=""){stopRouter();hideAll();elements.adminLoginMessage.textContent=message;elements.adminPassword.value="";elements.adminLogin.hidden=false;document.body.classList.remove("admin-loading");}
  function showShell(access){hideAll();elements.adminName.textContent=access.name;elements.adminRole.textContent=access.role;elements.adminShell.hidden=false;document.body.classList.remove("admin-loading");if(!routerStarted){window.AdminRouter.start(elements.adminRouteView);routerStarted=true;}}
  function showFatal(message){stopRouter();hideAll();elements.adminFatalMessage.textContent=message;elements.adminFatal.hidden=false;document.body.classList.remove("admin-loading");}
  function setLoginBusy(busy){elements.adminEmail.disabled=busy;elements.adminPassword.disabled=busy;elements.adminLoginButton.disabled=busy;elements.adminLoginButton.textContent=busy?"Verificando...":"Iniciar sesión";}
  function toggleMenu(open){elements.adminShell.classList.toggle("menu-open",open);elements.adminMenuButton.setAttribute("aria-expanded",String(open));elements.adminSidebarBackdrop.hidden=!open;}
  async function resolveCurrentAccess(){if(resolving)return;resolving=true;try{const result=await window.AdminAuthGuard.resolveAccess();if(result.status==="authorized")showShell(result.access);else if(result.status==="unauthorized"){await window.AdminAuthService.signOut();showLogin("Tu cuenta no tiene autorización administrativa.");}else showLogin();}catch(error){console.error("Admin access:",error);showFatal("No fue posible verificar el acceso administrativo.");}finally{resolving=false;}}
  async function handleLogin(event){event.preventDefault();if(!elements.adminLoginForm.reportValidity())return;setLoginBusy(true);elements.adminLoginMessage.textContent="";try{const session=await window.AdminAuthService.signIn(elements.adminEmail.value.trim(),elements.adminPassword.value);if(!session)throw new Error("Sesión no disponible.");const access=await window.AdminAuthGuard.verifyAccess();if(!access.authorized){await window.AdminAuthService.signOut();showLogin("Tu cuenta no tiene autorización administrativa.");return;}showShell(access);}catch(error){console.error("Admin login:",error);showLogin("No fue posible iniciar sesión. Verifica tus credenciales.");}finally{setLoginBusy(false);}}
  async function handleLogout(){elements.adminLogoutButton.disabled=true;try{await window.AdminAuthService.signOut();showLogin("Sesión cerrada correctamente.");}catch(error){console.error("Admin logout:",error);showFatal("No fue posible cerrar la sesión de forma segura.");}finally{elements.adminLogoutButton.disabled=false;}}
  async function initialize(){if(!resolveElements())return;elements.adminLoginForm.addEventListener("submit",handleLogin);elements.adminLogoutButton.addEventListener("click",handleLogout);elements.adminMenuButton.addEventListener("click",()=>toggleMenu(!elements.adminShell.classList.contains("menu-open")));elements.adminSidebarBackdrop.addEventListener("click",()=>toggleMenu(false));elements.adminShell.addEventListener("click",(event)=>{if(event.target.closest("[data-admin-route]"))toggleMenu(false);});const{data}=window.AdminAuthService.onAuthStateChange(({event})=>{if(event==="SIGNED_OUT"&&!resolving)showLogin();});authSubscription=data?.subscription||null;window.addEventListener("pagehide",()=>authSubscription?.unsubscribe?.(),{once:true});await resolveCurrentAccess();}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",initialize,{once:true});else initialize();
})();
