begin;

-- =========================================================
-- BODA J&M 2027
-- MESAS · FASE 5.1
-- Lista tabular + elementos visuales del plano
--
-- Agrega:
--   - mesa de los novios;
--   - pista de baile;
--   - persistencia de posición X/Y;
--   - auditoría de cambios de elementos;
--   - deja preparado el modelo para futuros elementos.
--
-- Los elementos visuales NO cuentan como mesas ni afectan
-- capacidad, confirmados o asignaciones.
-- =========================================================


-- =========================================================
-- 1. TABLA DE ELEMENTOS DEL PLANO
-- =========================================================

create table if not exists public.elementos_plano (
    id bigint generated by default as identity primary key,
    tipo text not null,
    nombre text not null,
    plano_x numeric(6,3),
    plano_y numeric(6,3),
    ancho numeric(6,3) not null default 18,
    alto numeric(6,3) not null default 12,
    activo boolean not null default true,
    fecha_creacion timestamptz not null default now(),
    fecha_actualizacion timestamptz not null default now(),

    constraint elementos_plano_tipo_check
        check (
            tipo in (
                'mesa_novios',
                'pista_baile',
                'mesa_pastel',
                'dj',
                'barra',
                'entrada',
                'escenario',
                'otro'
            )
        ),

    constraint elementos_plano_x_check
        check (plano_x is null or plano_x between 0 and 100),

    constraint elementos_plano_y_check
        check (plano_y is null or plano_y between 0 and 100),

    constraint elementos_plano_ancho_check
        check (ancho between 3 and 80),

    constraint elementos_plano_alto_check
        check (alto between 3 and 80)
);

create unique index if not exists elementos_plano_tipo_unico_activo
on public.elementos_plano(tipo)
where activo = true
  and tipo in ('mesa_novios', 'pista_baile');


-- =========================================================
-- 2. TRIGGER DE FECHA
-- =========================================================

create or replace function public.actualizar_fecha_elementos_plano()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
    new.fecha_actualizacion := now();
    return new;
end;
$$;

drop trigger if exists trg_elementos_plano_fecha
on public.elementos_plano;

create trigger trg_elementos_plano_fecha
before update on public.elementos_plano
for each row
execute function public.actualizar_fecha_elementos_plano();


-- =========================================================
-- 3. ELEMENTOS BASE
-- =========================================================

insert into public.elementos_plano (
    tipo,
    nombre,
    plano_x,
    plano_y,
    ancho,
    alto,
    activo
)
select
    'mesa_novios',
    'Mesa de los novios',
    50,
    12,
    22,
    10,
    true
where not exists (
    select 1
    from public.elementos_plano
    where tipo = 'mesa_novios'
      and activo = true
);

insert into public.elementos_plano (
    tipo,
    nombre,
    plano_x,
    plano_y,
    ancho,
    alto,
    activo
)
select
    'pista_baile',
    'Pista de baile',
    50,
    50,
    30,
    24,
    true
where not exists (
    select 1
    from public.elementos_plano
    where tipo = 'pista_baile'
      and activo = true
);


-- =========================================================
-- 4. AMPLIAR ACCIONES DE HISTORIAL
-- =========================================================

do $$
declare
    v_constraint text;
begin
    select c.conname
    into v_constraint
    from pg_constraint as c
    where c.conrelid = 'public.historial_mesas'::regclass
      and c.contype = 'c'
      and pg_get_constraintdef(c.oid) ilike '%accion%'
    limit 1;

    if v_constraint is not null then
        execute format(
            'alter table public.historial_mesas drop constraint %I',
            v_constraint
        );
    end if;

    alter table public.historial_mesas
        add constraint historial_mesas_accion_check
        check (
            accion in (
                'configuracion_inicial',
                'reconfigurado',
                'mesa_creada',
                'mesa_actualizada',
                'mesa_desactivada',
                'mesa_reactivada',
                'asignado',
                'reasignado',
                'asignacion_retirada',
                'sincronizado_confirmacion',
                'asignaciones_liberadas',
                'plano_actualizado',
                'elementos_plano_actualizados'
            )
        );
exception
    when duplicate_object then
        null;
end;
$$;


-- =========================================================
-- 5. LISTAR ELEMENTOS
-- =========================================================

create or replace function public.admin_listar_elementos_plano()
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
    v_items jsonb;
begin
    if auth.uid() is null
       or not private.es_administrador_activo() then
        raise exception 'Acceso administrativo no autorizado.'
            using errcode = '42501';
    end if;

    select coalesce(
        jsonb_agg(
            jsonb_build_object(
                'id', e.id,
                'tipo', e.tipo,
                'nombre', e.nombre,
                'plano_x', e.plano_x,
                'plano_y', e.plano_y,
                'ancho', e.ancho,
                'alto', e.alto,
                'activo', e.activo,
                'version', e.fecha_actualizacion
            )
            order by e.id
        ),
        '[]'::jsonb
    )
    into v_items
    from public.elementos_plano as e
    where e.activo = true;

    return jsonb_build_object(
        'schema_version', '1.0',
        'generated_at', now(),
        'data', jsonb_build_object(
            'items', v_items
        )
    );
end;
$$;


-- =========================================================
-- 6. GUARDAR ELEMENTOS
-- =========================================================

create or replace function public.admin_guardar_elementos_plano(
    p_elementos jsonb,
    p_motivo text
)
returns jsonb
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
    v_usuario_id uuid := auth.uid();
    v_admin_nombre text;
    v_motivo text := trim(coalesce(p_motivo, ''));

    v_item jsonb;
    v_id bigint;
    v_x numeric;
    v_y numeric;
    v_ancho numeric;
    v_alto numeric;

    v_anteriores jsonb;
    v_nuevos jsonb;
    v_total integer := 0;
begin
    if v_usuario_id is null
       or not private.es_administrador_activo() then
        raise exception 'Acceso administrativo no autorizado.'
            using errcode = '42501';
    end if;

    if p_elementos is null
       or jsonb_typeof(p_elementos) <> 'array'
       or jsonb_array_length(p_elementos) = 0 then
        raise exception 'ELEMENTOS_PLANO_INVALIDOS'
            using errcode = '22023';
    end if;

    if char_length(v_motivo) not between 1 and 1000 then
        raise exception 'MOTIVO_INVALIDO'
            using errcode = '22023';
    end if;

    select a.nombre
    into v_admin_nombre
    from public.administradores as a
    where a.usuario_id = v_usuario_id
      and a.activo = true
      and a.rol = 'administrador';

    if v_admin_nombre is null then
        raise exception 'Acceso administrativo no autorizado.'
            using errcode = '42501';
    end if;

    select coalesce(
        jsonb_agg(
            jsonb_build_object(
                'id', e.id,
                'tipo', e.tipo,
                'nombre', e.nombre,
                'x', e.plano_x,
                'y', e.plano_y,
                'ancho', e.ancho,
                'alto', e.alto
            )
            order by e.id
        ),
        '[]'::jsonb
    )
    into v_anteriores
    from public.elementos_plano as e
    where e.activo = true
      and e.id in (
          select (x ->> 'id')::bigint
          from jsonb_array_elements(p_elementos) as x
      );

    for v_item in
        select value
        from jsonb_array_elements(p_elementos)
    loop
        v_id := nullif(v_item ->> 'id', '')::bigint;
        v_x := nullif(v_item ->> 'x', '')::numeric;
        v_y := nullif(v_item ->> 'y', '')::numeric;
        v_ancho := nullif(v_item ->> 'ancho', '')::numeric;
        v_alto := nullif(v_item ->> 'alto', '')::numeric;

        if v_id is null
           or v_x is null
           or v_y is null
           or v_ancho is null
           or v_alto is null
           or v_x not between 0 and 100
           or v_y not between 0 and 100
           or v_ancho not between 3 and 80
           or v_alto not between 3 and 80 then
            raise exception 'ELEMENTO_PLANO_POSICION_INVALIDA'
                using errcode = '22023';
        end if;

        update public.elementos_plano
        set
            plano_x = round(v_x, 3),
            plano_y = round(v_y, 3),
            ancho = round(v_ancho, 3),
            alto = round(v_alto, 3)
        where id = v_id
          and activo = true;

        if not found then
            raise exception 'ELEMENTO_PLANO_NO_ENCONTRADO'
                using errcode = 'P0002';
        end if;

        v_total := v_total + 1;
    end loop;

    select coalesce(
        jsonb_agg(
            jsonb_build_object(
                'id', e.id,
                'tipo', e.tipo,
                'nombre', e.nombre,
                'x', e.plano_x,
                'y', e.plano_y,
                'ancho', e.ancho,
                'alto', e.alto
            )
            order by e.id
        ),
        '[]'::jsonb
    )
    into v_nuevos
    from public.elementos_plano as e
    where e.activo = true
      and e.id in (
          select (x ->> 'id')::bigint
          from jsonb_array_elements(p_elementos) as x
      );

    insert into public.historial_mesas (
        tipo_entidad,
        entidad_id,
        accion,
        datos_anteriores,
        datos_nuevos,
        modificado_por,
        administrador_nombre,
        motivo
    )
    values (
        'configuracion',
        null,
        'elementos_plano_actualizados',
        jsonb_build_object('elementos', v_anteriores),
        jsonb_build_object('elementos', v_nuevos),
        v_usuario_id,
        v_admin_nombre,
        v_motivo
    );

    return jsonb_build_object(
        'schema_version', '1.0',
        'generated_at', now(),
        'data', jsonb_build_object(
            'saved', true,
            'elementos_actualizados', v_total
        )
    );
end;
$$;


-- =========================================================
-- 7. PERMISOS
-- =========================================================

revoke all on public.elementos_plano from public, anon;
grant select on public.elementos_plano to authenticated;

revoke execute on function public.admin_listar_elementos_plano()
from public, anon;

grant execute on function public.admin_listar_elementos_plano()
to authenticated;

revoke execute on function public.admin_guardar_elementos_plano(jsonb, text)
from public, anon;

grant execute on function public.admin_guardar_elementos_plano(jsonb, text)
to authenticated;

commit;
