begin;

create table if not exists public.wedding_esenciales (
  id bigint generated by default as identity primary key,
  categoria text not null,
  titulo text not null,
  estado text not null default 'por_definir' check (estado in ('por_definir','buscando','elegido','contratado','listo','no_aplica')),
  notas text,
  orden integer not null default 0,
  fecha_actualizacion timestamptz not null default now(),
  unique (categoria, titulo)
);

alter table public.wedding_esenciales enable row level security;
revoke all on table public.wedding_esenciales from anon, authenticated;

insert into public.wedding_esenciales (categoria,titulo,orden) values
('Lugar y ceremonia','Lugar de la recepción',10),('Lugar y ceremonia','Ceremonia cristiana',20),('Lugar y ceremonia','Oficiante / pastor',30),('Lugar y ceremonia','Decoración de ceremonia',40),
('Recepción','Banquete',10),('Recepción','Bebidas y alcohol',20),('Recepción','Pastel',30),('Recepción','Música / DJ',40),('Recepción','Iluminación y audio',50),('Recepción','Centros de mesa',60),('Recepción','Decoración general',70),
('Foto y recuerdos','Fotografía',10),('Foto y recuerdos','Video',20),('Foto y recuerdos','Recuerdos para invitados',30),('Foto y recuerdos','Libro / dinámica de recuerdos',40),
('Novia','Vestido de novia',10),('Novia','Zapatos y accesorios',20),('Novia','Maquillaje',30),('Novia','Peinado',40),('Novia','Ramo',50),
('Novio','Traje del novio',10),('Novio','Zapatos y accesorios',20),
('Cortejo y familia','Vestidos de damas de honor',10),('Cortejo y familia','Trajes de caballeros de honor',20),('Cortejo y familia','Vestimenta de padres',30),
('Invitados','Invitaciones',10),('Invitados','Confirmaciones RSVP',20),('Invitados','Asignación de mesas',30),('Invitados','Mesa de regalos',40),
('Detalles finales','Anillos',10),('Detalles finales','Transporte',20),('Detalles finales','Hospedaje si aplica',30),('Detalles finales','Kit de emergencia',40),('Detalles finales','Cronograma del día',50)
on conflict (categoria,titulo) do nothing;

create or replace function public.admin_esenciales_resumen()
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_uid uuid:=auth.uid(); v_data jsonb;
begin
 if v_uid is null or not public.es_admin_activo(v_uid) then raise exception 'acceso_administrativo_no_autorizado'; end if;
 select jsonb_build_object(
  'schema_version','1.0','generated_at',now(),
  'data',jsonb_build_object(
   'resumen',jsonb_build_object(
    'total',count(*) filter(where estado<>'no_aplica'),
    'listos',count(*) filter(where estado='listo'),
    'contratados',count(*) filter(where estado='contratado'),
    'en_decision',count(*) filter(where estado in ('buscando','elegido')),
    'por_definir',count(*) filter(where estado='por_definir'),
    'porcentaje',case when count(*) filter(where estado<>'no_aplica')=0 then 0 else round(100.0*count(*) filter(where estado in ('listo','contratado'))/count(*) filter(where estado<>'no_aplica')) end
   ),
   'items',coalesce(jsonb_agg(jsonb_build_object('id',id,'categoria',categoria,'titulo',titulo,'estado',estado,'notas',notas,'orden',orden,'fecha_actualizacion',fecha_actualizacion) order by categoria,orden,titulo),'[]'::jsonb)
  )) into v_data from public.wedding_esenciales;
 return v_data;
end $$;

create or replace function public.admin_esenciales_actualizar(p_id bigint,p_estado text,p_notas text default null)
returns jsonb language plpgsql security definer set search_path=public as $$
begin
 if auth.uid() is null or not public.es_admin_activo(auth.uid()) then raise exception 'acceso_administrativo_no_autorizado'; end if;
 if p_estado not in ('por_definir','buscando','elegido','contratado','listo','no_aplica') then raise exception 'estado_invalido'; end if;
 update public.wedding_esenciales set estado=p_estado,notas=nullif(trim(coalesce(p_notas,'')),''),fecha_actualizacion=now() where id=p_id;
 if not found then raise exception 'esencial_no_encontrado'; end if;
 return jsonb_build_object('schema_version','1.0','generated_at',now(),'data',jsonb_build_object('ok',true,'id',p_id));
end $$;

revoke execute on function public.admin_esenciales_resumen() from public, anon;
revoke execute on function public.admin_esenciales_actualizar(bigint,text,text) from public, anon;
grant execute on function public.admin_esenciales_resumen() to authenticated;
grant execute on function public.admin_esenciales_actualizar(bigint,text,text) to authenticated;
commit;
