begin;

create table if not exists public.wedding_planner_esencial_secciones (
  id bigint generated by default as identity primary key,
  nombre text not null,
  es_personalizada boolean not null default true,
  activo boolean not null default true,
  creado_at timestamptz not null default now(),
  actualizado_at timestamptz not null default now(),
  constraint wedding_planner_esencial_secciones_nombre_chk
    check (char_length(btrim(nombre)) between 1 and 80)
);

create unique index if not exists wedding_planner_esencial_secciones_nombre_uq
  on public.wedding_planner_esencial_secciones (lower(btrim(nombre)))
  where activo;

alter table public.wedding_planner_esencial_secciones enable row level security;

revoke all on table public.wedding_planner_esencial_secciones from public, anon, authenticated;

create or replace function public.admin_esenciales_listar_secciones()
returns jsonb
language plpgsql
security definer
set search_path = public, private
as $$
declare
  v_items jsonb;
begin
  if not private.es_administrador_activo() then
    raise exception 'ACCESO_ADMINISTRATIVO_NO_AUTORIZADO';
  end if;

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'id', s.id,
        'nombre', s.nombre,
        'es_personalizada', s.es_personalizada
      )
      order by lower(s.nombre)
    ),
    '[]'::jsonb
  )
  into v_items
  from public.wedding_planner_esencial_secciones s
  where s.activo;

  return jsonb_build_object(
    'schema_version', '1.0',
    'generated_at', now(),
    'data', jsonb_build_object('items', v_items)
  );
end;
$$;

revoke execute on function public.admin_esenciales_listar_secciones() from public, anon;
grant execute on function public.admin_esenciales_listar_secciones() to authenticated;

create or replace function public.admin_esenciales_guardar_seccion(p_nombre text)
returns jsonb
language plpgsql
security definer
set search_path = public, private
as $$
declare
  v_nombre text := btrim(coalesce(p_nombre, ''));
  v_id bigint;
begin
  if not private.es_administrador_activo() then
    raise exception 'ACCESO_ADMINISTRATIVO_NO_AUTORIZADO';
  end if;

  if char_length(v_nombre) < 1 or char_length(v_nombre) > 80 then
    raise exception 'NOMBRE_SECCION_INVALIDO';
  end if;

  select id into v_id
  from public.wedding_planner_esencial_secciones
  where lower(btrim(nombre)) = lower(v_nombre)
  order by activo desc, id
  limit 1;

  if v_id is null then
    insert into public.wedding_planner_esencial_secciones(nombre)
    values (v_nombre)
    returning id into v_id;
  else
    update public.wedding_planner_esencial_secciones
       set nombre = v_nombre,
           activo = true,
           actualizado_at = now()
     where id = v_id;
  end if;

  return jsonb_build_object(
    'schema_version', '1.0',
    'generated_at', now(),
    'data', jsonb_build_object(
      'id', v_id,
      'nombre', v_nombre
    )
  );
end;
$$;

revoke execute on function public.admin_esenciales_guardar_seccion(text) from public, anon;
grant execute on function public.admin_esenciales_guardar_seccion(text) to authenticated;

commit;
