begin;

-- =========================================================
-- BODA J&M 2027
-- FASE 10.0 · PADRINOS V1
-- Ejecutar una sola vez en Supabase.
-- =========================================================

create table if not exists public.wedding_padrinazgos (
  id bigint generated by default as identity primary key,
  tipo text not null,
  estado text not null default 'por_definir',
  invitado_1_id bigint,
  invitado_1_nombre text,
  invitado_2_id bigint,
  invitado_2_nombre text,
  notas text,
  activo boolean not null default true,
  orden integer not null default 100,
  es_base boolean not null default false,
  creado_at timestamptz not null default now(),
  actualizado_at timestamptz not null default now(),
  constraint wedding_padrinazgos_tipo_chk check (char_length(btrim(tipo)) between 1 and 100),
  constraint wedding_padrinazgos_estado_chk check (estado in ('por_definir','invitados','confirmados','rechazado')),
  constraint wedding_padrinazgos_notas_chk check (notas is null or char_length(notas) <= 2000)
);

create unique index if not exists wedding_padrinazgos_tipo_activo_uq
  on public.wedding_padrinazgos(lower(btrim(tipo)))
  where activo;

alter table public.wedding_padrinazgos enable row level security;
revoke all on table public.wedding_padrinazgos from public, anon, authenticated;

insert into public.wedding_padrinazgos(tipo, estado, activo, orden, es_base)
select x.tipo, 'por_definir', true, x.orden, true
from (
  values
    ('Anillos',10),
    ('Arras',20),
    ('Lazo',30),
    ('Biblia',40),
    ('Velación',50),
    ('Ramo',60),
    ('Pastel',70),
    ('Brindis',80)
) as x(tipo,orden)
where not exists (
  select 1
  from public.wedding_padrinazgos p
  where lower(btrim(p.tipo)) = lower(btrim(x.tipo))
);

create or replace function public.admin_padrinos_resumen()
returns jsonb
language plpgsql
security definer
set search_path = public, private
as $$
declare
  v_items jsonb;
  v_total integer;
  v_confirmados integer;
  v_invitados integer;
  v_por_definir integer;
  v_rechazados integer;
  v_deshabilitados integer;
begin
  if not private.es_administrador_activo() then
    raise exception 'ACCESO_ADMINISTRATIVO_NO_AUTORIZADO';
  end if;

  select
    count(*) filter (where activo),
    count(*) filter (where activo and estado = 'confirmados'),
    count(*) filter (where activo and estado = 'invitados'),
    count(*) filter (where activo and estado = 'por_definir'),
    count(*) filter (where activo and estado = 'rechazado'),
    count(*) filter (where not activo)
  into v_total, v_confirmados, v_invitados, v_por_definir, v_rechazados, v_deshabilitados
  from public.wedding_padrinazgos;

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'id', p.id,
        'tipo', p.tipo,
        'estado', p.estado,
        'invitado_1_id', p.invitado_1_id,
        'invitado_1_nombre', p.invitado_1_nombre,
        'invitado_2_id', p.invitado_2_id,
        'invitado_2_nombre', p.invitado_2_nombre,
        'notas', p.notas,
        'activo', p.activo,
        'orden', p.orden,
        'es_base', p.es_base,
        'actualizado_at', p.actualizado_at
      )
      order by p.activo desc, p.orden, lower(p.tipo)
    ),
    '[]'::jsonb
  )
  into v_items
  from public.wedding_padrinazgos p;

  return jsonb_build_object(
    'schema_version','1.0',
    'generated_at',now(),
    'data',jsonb_build_object(
      'summary',jsonb_build_object(
        'total',v_total,
        'confirmados',v_confirmados,
        'invitados',v_invitados,
        'por_definir',v_por_definir,
        'rechazados',v_rechazados,
        'deshabilitados',v_deshabilitados
      ),
      'items',v_items
    )
  );
end;
$$;

revoke execute on function public.admin_padrinos_resumen() from public, anon;
grant execute on function public.admin_padrinos_resumen() to authenticated;


create or replace function public.admin_padrinos_guardar(
  p_id bigint,
  p_tipo text,
  p_estado text,
  p_invitado_1_id bigint,
  p_invitado_1_nombre text,
  p_invitado_2_id bigint,
  p_invitado_2_nombre text,
  p_notas text
)
returns jsonb
language plpgsql
security definer
set search_path = public, private
as $$
declare
  v_id bigint;
  v_tipo text := btrim(coalesce(p_tipo,''));
  v_estado text := coalesce(nullif(btrim(p_estado),''),'por_definir');
  v_notas text := nullif(btrim(coalesce(p_notas,'')),'');
begin
  if not private.es_administrador_activo() then
    raise exception 'ACCESO_ADMINISTRATIVO_NO_AUTORIZADO';
  end if;

  if char_length(v_tipo) < 1 or char_length(v_tipo) > 100 then
    raise exception 'TIPO_PADRINAZGO_INVALIDO';
  end if;

  if v_estado not in ('por_definir','invitados','confirmados','rechazado') then
    raise exception 'ESTADO_PADRINAZGO_INVALIDO';
  end if;

  if v_notas is not null and char_length(v_notas) > 2000 then
    raise exception 'NOTAS_PADRINAZGO_INVALIDAS';
  end if;

  if p_invitado_1_id is not null and p_invitado_2_id is not null and p_invitado_1_id = p_invitado_2_id then
    raise exception 'PADRINOS_DUPLICADOS';
  end if;

  if p_id is null then
    insert into public.wedding_padrinazgos(
      tipo,estado,invitado_1_id,invitado_1_nombre,invitado_2_id,invitado_2_nombre,notas,activo,orden,es_base
    )
    values(
      v_tipo,v_estado,p_invitado_1_id,nullif(btrim(coalesce(p_invitado_1_nombre,'')),''),
      p_invitado_2_id,nullif(btrim(coalesce(p_invitado_2_nombre,'')),''),
      v_notas,true,100,false
    )
    returning id into v_id;
  else
    update public.wedding_padrinazgos
       set tipo = v_tipo,
           estado = v_estado,
           invitado_1_id = p_invitado_1_id,
           invitado_1_nombre = nullif(btrim(coalesce(p_invitado_1_nombre,'')),''),
           invitado_2_id = p_invitado_2_id,
           invitado_2_nombre = nullif(btrim(coalesce(p_invitado_2_nombre,'')),''),
           notas = v_notas,
           actualizado_at = now()
     where id = p_id
    returning id into v_id;

    if v_id is null then
      raise exception 'PADRINAZGO_NO_ENCONTRADO';
    end if;
  end if;

  return jsonb_build_object(
    'schema_version','1.0',
    'generated_at',now(),
    'data',jsonb_build_object('ok',true,'id',v_id)
  );
end;
$$;

revoke execute on function public.admin_padrinos_guardar(bigint,text,text,bigint,text,bigint,text,text) from public, anon;
grant execute on function public.admin_padrinos_guardar(bigint,text,text,bigint,text,bigint,text,text) to authenticated;


create or replace function public.admin_padrinos_cambiar_activo(
  p_id bigint,
  p_activo boolean
)
returns jsonb
language plpgsql
security definer
set search_path = public, private
as $$
begin
  if not private.es_administrador_activo() then
    raise exception 'ACCESO_ADMINISTRATIVO_NO_AUTORIZADO';
  end if;

  update public.wedding_padrinazgos
     set activo = coalesce(p_activo,true),
         actualizado_at = now()
   where id = p_id;

  if not found then
    raise exception 'PADRINAZGO_NO_ENCONTRADO';
  end if;

  return jsonb_build_object(
    'schema_version','1.0',
    'generated_at',now(),
    'data',jsonb_build_object('ok',true,'id',p_id,'activo',coalesce(p_activo,true))
  );
end;
$$;

revoke execute on function public.admin_padrinos_cambiar_activo(bigint,boolean) from public, anon;
grant execute on function public.admin_padrinos_cambiar_activo(bigint,boolean) to authenticated;

commit;

notify pgrst, 'reload schema';
