begin;

-- =========================================================
-- BODA J&M 2027
-- FASE 10.1.2 · RESET LIMPIO DEL MÓDULO PADRINOS
-- Reinicia únicamente los datos del módulo Padrinos.
-- NO afecta Invitaciones, Mesas, Planeación, Presupuesto,
-- Contratos, Esenciales ni ningún otro módulo.
-- =========================================================

-- 1) Quitamos funciones anteriores para evitar firmas obsoletas.
drop function if exists public.admin_padrinos_guardar(bigint,text,text,bigint,text,bigint,text,text);
drop function if exists public.admin_padrinos_guardar(bigint,text,text,bigint,text,text,text);
drop function if exists public.admin_padrinos_resumen();
drop function if exists public.admin_padrinos_cambiar_activo(bigint,boolean);

-- 2) Recreamos desde cero únicamente la tabla de padrinos.
drop table if exists public.wedding_padrinazgos cascade;

create table public.wedding_padrinazgos (
  id bigint generated by default as identity primary key,
  tipo text not null,
  estado text not null default 'por_definir',
  invitacion_id bigint,
  invitacion_nombre text,
  nombres_padrinos text,
  notas text,
  activo boolean not null default true,
  orden integer not null default 100,
  es_base boolean not null default false,
  creado_at timestamptz not null default now(),
  actualizado_at timestamptz not null default now(),

  constraint wedding_padrinazgos_tipo_chk
    check (char_length(btrim(tipo)) between 1 and 100),

  constraint wedding_padrinazgos_estado_chk
    check (estado in ('por_definir','confirmado')),

  constraint wedding_padrinazgos_nombres_chk
    check (nombres_padrinos is null or char_length(nombres_padrinos) <= 250),

  constraint wedding_padrinazgos_notas_chk
    check (notas is null or char_length(notas) <= 2000)
);

create unique index wedding_padrinazgos_tipo_activo_uq
  on public.wedding_padrinazgos(lower(btrim(tipo)))
  where activo;

alter table public.wedding_padrinazgos enable row level security;

revoke all on table public.wedding_padrinazgos from public, anon, authenticated;

-- 3) Cargamos la estructura base.
insert into public.wedding_padrinazgos(tipo, estado, activo, orden, es_base)
values
  ('Anillos','por_definir',true,10,true),
  ('Arras','por_definir',true,20,true),
  ('Lazo','por_definir',true,30,true),
  ('Biblia','por_definir',true,40,true),
  ('Velación','por_definir',true,50,true),
  ('Ramo','por_definir',true,60,true),
  ('Pastel','por_definir',true,70,true),
  ('Brindis','por_definir',true,80,true);

-- 4) Resumen / listado.
create or replace function public.admin_padrinos_resumen()
returns jsonb
language plpgsql
security definer
set search_path = public, private
as $$
declare
  v_items jsonb;
  v_total integer;
  v_confirmados integer;
  v_por_definir integer;
  v_deshabilitados integer;
begin
  if not private.es_administrador_activo() then
    raise exception 'ACCESO_ADMINISTRATIVO_NO_AUTORIZADO';
  end if;

  select
    count(*) filter (where activo),
    count(*) filter (where activo and estado = 'confirmado'),
    count(*) filter (where activo and estado = 'por_definir'),
    count(*) filter (where not activo)
  into
    v_total,
    v_confirmados,
    v_por_definir,
    v_deshabilitados
  from public.wedding_padrinazgos;

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'id', p.id,
        'tipo', p.tipo,
        'estado', p.estado,
        'invitacion_id', p.invitacion_id,
        'invitacion_nombre', p.invitacion_nombre,
        'nombres_padrinos', p.nombres_padrinos,
        'notas', p.notas,
        'activo', p.activo,
        'orden', p.orden,
        'es_base', p.es_base,
        'actualizado_at', p.actualizado_at
      )
      order by p.activo desc, p.orden, lower(p.tipo)
    ),
    '[]'::jsonb
  )
  into v_items
  from public.wedding_padrinazgos p;

  return jsonb_build_object(
    'schema_version','1.1',
    'generated_at',now(),
    'data',jsonb_build_object(
      'summary',jsonb_build_object(
        'total',v_total,
        'confirmados',v_confirmados,
        'por_definir',v_por_definir,
        'deshabilitados',v_deshabilitados
      ),
      'items',v_items
    )
  );
end;
$$;

revoke execute on function public.admin_padrinos_resumen() from public, anon;
grant execute on function public.admin_padrinos_resumen() to authenticated;

-- 5) Crear / editar.
create or replace function public.admin_padrinos_guardar(
  p_id bigint,
  p_tipo text,
  p_estado text,
  p_invitacion_id bigint,
  p_invitacion_nombre text,
  p_nombres_padrinos text,
  p_notas text
)
returns jsonb
language plpgsql
security definer
set search_path = public, private
as $$
declare
  v_id bigint;
  v_tipo text := btrim(coalesce(p_tipo,''));
  v_estado text := coalesce(nullif(btrim(p_estado),''),'por_definir');
  v_invitacion_nombre text := nullif(btrim(coalesce(p_invitacion_nombre,'')),'');
  v_nombres text := nullif(btrim(coalesce(p_nombres_padrinos,'')),'');
  v_notas text := nullif(btrim(coalesce(p_notas,'')),'');
begin
  if not private.es_administrador_activo() then
    raise exception 'ACCESO_ADMINISTRATIVO_NO_AUTORIZADO';
  end if;

  if char_length(v_tipo) < 1 or char_length(v_tipo) > 100 then
    raise exception 'TIPO_PADRINO_INVALIDO';
  end if;

  if v_estado not in ('por_definir','confirmado') then
    raise exception 'ESTADO_PADRINO_INVALIDO';
  end if;

  if v_nombres is not null and char_length(v_nombres) > 250 then
    raise exception 'NOMBRES_PADRINOS_INVALIDOS';
  end if;

  if v_notas is not null and char_length(v_notas) > 2000 then
    raise exception 'NOTAS_PADRINO_INVALIDAS';
  end if;

  if p_id is null then
    insert into public.wedding_padrinazgos(
      tipo,
      estado,
      invitacion_id,
      invitacion_nombre,
      nombres_padrinos,
      notas,
      activo,
      orden,
      es_base
    )
    values(
      v_tipo,
      v_estado,
      p_invitacion_id,
      v_invitacion_nombre,
      v_nombres,
      v_notas,
      true,
      100,
      false
    )
    returning id into v_id;
  else
    update public.wedding_padrinazgos
       set tipo = v_tipo,
           estado = v_estado,
           invitacion_id = p_invitacion_id,
           invitacion_nombre = v_invitacion_nombre,
           nombres_padrinos = v_nombres,
           notas = v_notas,
           actualizado_at = now()
     where id = p_id
    returning id into v_id;

    if v_id is null then
      raise exception 'PADRINO_NO_ENCONTRADO';
    end if;
  end if;

  return jsonb_build_object(
    'schema_version','1.1',
    'generated_at',now(),
    'data',jsonb_build_object(
      'ok',true,
      'id',v_id
    )
  );
end;
$$;

revoke execute on function public.admin_padrinos_guardar(bigint,text,text,bigint,text,text,text) from public, anon;
grant execute on function public.admin_padrinos_guardar(bigint,text,text,bigint,text,text,text) to authenticated;

-- 6) Habilitar / deshabilitar.
create or replace function public.admin_padrinos_cambiar_activo(
  p_id bigint,
  p_activo boolean
)
returns jsonb
language plpgsql
security definer
set search_path = public, private
as $$
begin
  if not private.es_administrador_activo() then
    raise exception 'ACCESO_ADMINISTRATIVO_NO_AUTORIZADO';
  end if;

  update public.wedding_padrinazgos
     set activo = coalesce(p_activo,true),
         actualizado_at = now()
   where id = p_id;

  if not found then
    raise exception 'PADRINO_NO_ENCONTRADO';
  end if;

  return jsonb_build_object(
    'schema_version','1.1',
    'generated_at',now(),
    'data',jsonb_build_object(
      'ok',true,
      'id',p_id,
      'activo',coalesce(p_activo,true)
    )
  );
end;
$$;

revoke execute on function public.admin_padrinos_cambiar_activo(bigint,boolean) from public, anon;
grant execute on function public.admin_padrinos_cambiar_activo(bigint,boolean) to authenticated;

commit;

notify pgrst, 'reload schema';
