-- =========================================================
-- FASE 12.2 · FECHA LÍMITE RSVP CONFIGURABLE
-- 1) Permite consultar y actualizar la fecha límite desde Administración.
-- 2) Registra cada cambio con trazabilidad.
-- 3) Evita convertir físicamente en "no_asistira" a quien simplemente no respondió.
-- 4) La invitación pública continúa usando configuracion.fecha_limite_rsvp.
-- =========================================================

begin;

create table if not exists public.historial_configuracion_rsvp (
    id bigint generated by default as identity primary key,
    clave text not null,
    valor_anterior jsonb,
    valor_nuevo jsonb not null,
    motivo text not null,
    modificado_por uuid not null,
    administrador_nombre text,
    fecha_evento timestamptz not null default now()
);

alter table public.historial_configuracion_rsvp enable row level security;
revoke all on table public.historial_configuracion_rsvp from public, anon, authenticated;

create or replace function public.admin_obtener_configuracion_rsvp()
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_fecha text;
    v_rsvp boolean;
    v_modificaciones boolean;
begin
    if auth.uid() is null or not private.es_administrador_activo() then
        raise exception 'Acceso administrativo no autorizado.' using errcode = '42501';
    end if;

    select valor #>> '{}' into v_fecha
      from public.configuracion where clave = 'fecha_limite_rsvp';
    select coalesce((valor #>> '{}')::boolean, true) into v_rsvp
      from public.configuracion where clave = 'rsvp_activo';
    select coalesce((valor #>> '{}')::boolean, true) into v_modificaciones
      from public.configuracion where clave = 'permitir_modificaciones';

    return jsonb_build_object(
        'schema_version','1.0',
        'generated_at',now(),
        'data',jsonb_build_object(
            'fecha_limite_rsvp',v_fecha,
            'rsvp_activo',coalesce(v_rsvp,true),
            'permitir_modificaciones',coalesce(v_modificaciones,true)
        )
    );
end;
$$;

create or replace function public.admin_actualizar_fecha_limite_rsvp(
    p_fecha date,
    p_motivo text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_motivo text := trim(coalesce(p_motivo,''));
    v_anterior jsonb;
    v_nuevo_text text;
    v_nuevo jsonb;
    v_admin_nombre text;
begin
    if auth.uid() is null or not private.es_administrador_activo() then
        raise exception 'Acceso administrativo no autorizado.' using errcode = '42501';
    end if;
    if p_fecha is null then
        raise exception 'FECHA_LIMITE_INVALIDA' using errcode = '22023';
    end if;
    if char_length(v_motivo) < 3 or char_length(v_motivo) > 500 then
        raise exception 'MOTIVO_INVALIDO' using errcode = '22023';
    end if;

    -- La boda es en México; el corte se aplica al final del día seleccionado.
    v_nuevo_text := to_char(p_fecha,'YYYY-MM-DD') || 'T23:59:59-06:00';
    v_nuevo := to_jsonb(v_nuevo_text);

    select valor into v_anterior
      from public.configuracion
     where clave = 'fecha_limite_rsvp'
     for update;

    insert into public.configuracion(clave,valor,descripcion)
    values('fecha_limite_rsvp',v_nuevo,'Fecha límite para confirmar o modificar asistencia.')
    on conflict (clave) do update
       set valor = excluded.valor,
           descripcion = excluded.descripcion,
           fecha_actualizacion = now();

    select a.nombre into v_admin_nombre
      from public.administradores a
     where a.usuario_id = auth.uid()
       and a.activo = true
     limit 1;

    insert into public.historial_configuracion_rsvp(
        clave, valor_anterior, valor_nuevo, motivo, modificado_por, administrador_nombre
    ) values(
        'fecha_limite_rsvp', v_anterior, v_nuevo, v_motivo, auth.uid(), v_admin_nombre
    );

    return jsonb_build_object(
        'schema_version','1.0',
        'generated_at',now(),
        'data',jsonb_build_object(
            'updated',true,
            'fecha_limite_rsvp',v_nuevo_text,
            'administrador_nombre',v_admin_nombre
        )
    );
end;
$$;

revoke execute on function public.admin_obtener_configuracion_rsvp() from public, anon;
grant execute on function public.admin_obtener_configuracion_rsvp() to authenticated;
revoke execute on function public.admin_actualizar_fecha_limite_rsvp(date,text) from public, anon;
grant execute on function public.admin_actualizar_fecha_limite_rsvp(date,text) to authenticated;

-- Sustituye la Fase 12.1: listar confirmaciones NO debe materializar
-- automáticamente una negativa para quien nunca respondió.
create or replace function public.admin_listar_confirmaciones(
    p_busqueda text default null,
    p_grupo text default null,
    p_estado text default null,
    p_activo boolean default null,
    p_pagina integer default 1,
    p_tamano_pagina integer default 20
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_busqueda text := nullif(trim(coalesce(p_busqueda, '')), '');
    v_grupo text := nullif(trim(coalesce(p_grupo, '')), '');
    v_estado text := nullif(trim(coalesce(p_estado, '')), '');
    v_total integer;
    v_total_paginas integer;
    v_offset integer;
    v_items jsonb;
begin
    if auth.uid() is null or not private.es_administrador_activo() then
        raise exception 'Acceso administrativo no autorizado.' using errcode = '42501';
    end if;
    if p_pagina is null or p_pagina < 1 then raise exception 'PAGINA_INVALIDA' using errcode='22023'; end if;
    if p_tamano_pagina is null or p_tamano_pagina not in (10,20,50) then raise exception 'TAMANO_PAGINA_INVALIDO' using errcode='22023'; end if;
    if v_grupo is not null and v_grupo not in ('Familia Marcos','Familia Jess','Amigos Marcos','Amigos Jess') then raise exception 'GRUPO_INVALIDO' using errcode='22023'; end if;
    if v_estado is not null and v_estado not in ('confirmado','no_asistira') then raise exception 'ESTADO_INVALIDO' using errcode='22023'; end if;
    if v_busqueda is not null and char_length(v_busqueda) > 150 then raise exception 'BUSQUEDA_DEMASIADO_LARGA' using errcode='22023'; end if;

    select count(*) into v_total
    from public.confirmaciones c join public.invitados i on i.id=c.invitado_id
    where (v_busqueda is null or i.nombre ilike '%'||v_busqueda||'%' or i.codigo ilike '%'||v_busqueda||'%' or i.grupo ilike '%'||v_busqueda||'%')
      and (v_grupo is null or i.grupo=v_grupo)
      and (v_estado is null or c.estado=v_estado)
      and (p_activo is null or i.activo=p_activo);

    v_total_paginas := case when v_total=0 then 0 else ceil(v_total::numeric/p_tamano_pagina)::integer end;
    if v_total_paginas>0 and p_pagina>v_total_paginas then raise exception 'PAGINA_FUERA_DE_RANGO' using errcode='22023'; end if;
    v_offset := (p_pagina-1)*p_tamano_pagina;

    select coalesce(jsonb_agg(jsonb_build_object(
        'invitado_id',q.invitado_id,'codigo',q.codigo,'nombre',q.nombre,'grupo',q.grupo,
        'invitacion_activa',q.invitacion_activa,
        'cupo',jsonb_build_object('adultos',q.adultos_asignados,'ninos',q.ninos_asignados,'total',q.cupo_total),
        'confirmacion',jsonb_build_object(
            'estado',q.estado,'adultos',q.adultos_confirmados,'ninos',q.ninos_confirmados,'total',q.total_confirmado,
            'tiene_mensaje',q.mensaje is not null,'tiene_actualizaciones',q.tiene_actualizaciones,
            'fecha_confirmacion',q.fecha_confirmacion,'fecha_actualizacion',q.fecha_actualizacion
        )
    ) order by q.fecha_actualizacion desc,q.invitado_id desc),'[]'::jsonb)
    into v_items
    from (
      select i.id invitado_id,i.codigo,i.nombre,i.grupo,i.activo invitacion_activa,
             i.adultos_asignados::integer,i.ninos_asignados::integer,(i.adultos_asignados+i.ninos_asignados)::integer cupo_total,
             c.estado,c.adultos_confirmados::integer,c.ninos_confirmados::integer,
             (c.adultos_confirmados+c.ninos_confirmados)::integer total_confirmado,
             c.mensaje,c.fecha_confirmacion,c.fecha_actualizacion,
             exists(select 1 from public.historial_confirmaciones h where h.invitado_id=i.id and h.accion='actualizada') tiene_actualizaciones
      from public.confirmaciones c join public.invitados i on i.id=c.invitado_id
      where (v_busqueda is null or i.nombre ilike '%'||v_busqueda||'%' or i.codigo ilike '%'||v_busqueda||'%' or i.grupo ilike '%'||v_busqueda||'%')
        and (v_grupo is null or i.grupo=v_grupo)
        and (v_estado is null or c.estado=v_estado)
        and (p_activo is null or i.activo=p_activo)
      order by c.fecha_actualizacion desc,i.id desc
      limit p_tamano_pagina offset v_offset
    ) q;

    return jsonb_build_object('schema_version','1.0','generated_at',now(),'data',jsonb_build_object(
      'items',v_items,'pagination',jsonb_build_object('page',p_pagina,'page_size',p_tamano_pagina,'total_items',v_total,
      'total_pages',v_total_paginas,'has_previous',p_pagina>1,'has_next',v_total_paginas>0 and p_pagina<v_total_paginas)
    ));
end;
$$;

revoke execute on function public.admin_listar_confirmaciones(text,text,text,boolean,integer,integer) from public, anon;
grant execute on function public.admin_listar_confirmaciones(text,text,text,boolean,integer,integer) to authenticated;

commit;
